### ISSUE TITLE
Is the camera upside down?

### ISSUE THREAD

**Issue by chushengniudu** [Rajawali/Rajawali#1824]
I used the latest Rajawali to play 360 panoramic video and found that the camera is rotating in the direction is reversed, the old Rajawali will not be the problem, I try to solve the problem, but did not succeed.

Is there any good way to solve this problem?

**Comment by jwoolston** [comment]
When you say camera are you referring to the Rajawali Camera class? If so, yes there was previously an error in the coordinate system and it has been corrected.

**Comment by chushengniudu** [comment]
I downloaded the latest package https://github.com/Rajawali/Rajawali, extract the project, run Cardboard integration But still have this problem:

The camera rotates, but the video rotates in the opposite direction. Upside down. Left and right reversed.

Is the item I downloaded is not the latest item?

**Comment by jwoolston** [comment]
#1854 should resolve this.
